apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: bmonkman/finn-api:latest
          resources:
            requests:
              memory: 64Mi
              cpu: 0.01
            limits:
              memory: 128Mi
              cpu: 0.5
          livenessProbe:
            httpGet:
              port: http
              path: v1/status/alive
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: http
              path: v1/status/ready
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          ports:
            - containerPort: 80
              name: http
          env:
          - name: SERVER_PORT
            value: "80"
          - name: SERVER_HOST
            value: "0.0.0.0"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-service
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 60
